
package VistasAdminGeneral;

import Controladores.ControladorRegistroMedicoAdmi;
import Excepciones.CorreoRegistradoException;
import Excepciones.IdentificacionNoExisteException;
import Excepciones.InformacionMedicoPacienteException;
import Excepciones.RegistradoException;
import Modelos.Medico;
import Modelos.Persona;
import java.awt.Color;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diazje
 */
public class VentanaGestionMedico extends javax.swing.JFrame {

    DefaultTableModel modelo1;
    private ControladorRegistroMedicoAdmi controladorMedico;
    int xMouse, yMouse;
    private Persona administrador;

    public VentanaGestionMedico(Persona administrador) {
        initComponents();
        this.administrador = administrador;
        modelo1 = (DefaultTableModel)tablaMedicos.getModel();
        this.controladorMedico = new ControladorRegistroMedicoAdmi();
        actualizarTabla();
        actualizarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        barraLateral = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        lblCerrar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMedicos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtIdBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtConfirmarContrasenia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        cboEspecialidades = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        btnRegistrarse = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtContrasenia1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cboGenero = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        lblVolver = new javax.swing.JLabel();
        btnVolver = new javax.swing.JPanel();
        lblRegresar = new javax.swing.JPanel();
        lblVolver1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jSeparator13 = new javax.swing.JSeparator();
        cboFinMin = new javax.swing.JComboBox<>();
        jSeparator14 = new javax.swing.JSeparator();
        cboFinHora = new javax.swing.JComboBox<>();
        jSeparator15 = new javax.swing.JSeparator();
        cboInicioHora = new javax.swing.JComboBox<>();
        jSeparator16 = new javax.swing.JSeparator();
        cboInicioMin = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(200, 230, 237));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 20, 730));

        jPanel7.setBackground(new java.awt.Color(200, 230, 237));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 860, -1));

        barraLateral.setBackground(new java.awt.Color(255, 255, 255));
        barraLateral.setForeground(new java.awt.Color(255, 255, 255));
        barraLateral.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraLateralMouseDragged(evt);
            }
        });
        barraLateral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraLateralMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        lblCerrar.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        lblCerrar.setForeground(new java.awt.Color(0, 0, 0));
        lblCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-cerrar-ventana-40.png"))); // NOI18N
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblCerrar))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblCerrar))
        );

        javax.swing.GroupLayout barraLateralLayout = new javax.swing.GroupLayout(barraLateral);
        barraLateral.setLayout(barraLateralLayout);
        barraLateralLayout.setHorizontalGroup(
            barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraLateralLayout.createSequentialGroup()
                .addGap(0, 820, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        barraLateralLayout.setVerticalGroup(
            barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraLateralLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(barraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaMedicos.setBackground(new java.awt.Color(255, 255, 255));
        tablaMedicos.setForeground(new java.awt.Color(103, 160, 174));
        tablaMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Id", "Usuario", "Contraseña"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaMedicos.setSelectionBackground(new java.awt.Color(103, 160, 174));
        tablaMedicos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tablaMedicos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 370, 470));

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(103, 160, 174));
        jLabel1.setText("Ingrese un id:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 30));

        txtIdBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtIdBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdBuscarKeyTyped(evt);
            }
        });
        jPanel2.add(txtIdBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 130, -1));

        btnBuscar.setBackground(new java.awt.Color(103, 160, 174));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 106, 31));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 640));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo280_1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 250, 80));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(103, 160, 174));
        jLabel3.setText("Registra un Médico");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));

        jLabel4.setForeground(new java.awt.Color(103, 160, 174));
        jLabel4.setText("Especialización");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, -1));

        txtConfirmarContrasenia.setForeground(new java.awt.Color(0, 0, 0));
        txtConfirmarContrasenia.setBorder(null);
        jPanel1.add(txtConfirmarContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 590, 180, -1));

        jLabel5.setForeground(new java.awt.Color(103, 160, 174));
        jLabel5.setText("Hora final");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, -1, -1));

        jLabel6.setForeground(new java.awt.Color(103, 160, 174));
        jLabel6.setText("Nombres");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        txtNombres.setForeground(new java.awt.Color(0, 0, 0));
        txtNombres.setBorder(null);
        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 180, -1));

        jLabel7.setForeground(new java.awt.Color(103, 160, 174));
        jLabel7.setText("Apellidos:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, -1, -1));

        txtApellidos.setForeground(new java.awt.Color(0, 0, 0));
        txtApellidos.setBorder(null);
        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosKeyTyped(evt);
            }
        });
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 180, -1));

        jLabel8.setForeground(new java.awt.Color(103, 160, 174));
        jLabel8.setText("Edad");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, -1, -1));

        txtEdad.setForeground(new java.awt.Color(0, 0, 0));
        txtEdad.setBorder(null);
        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadKeyTyped(evt);
            }
        });
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 180, -1));

        jLabel9.setForeground(new java.awt.Color(103, 160, 174));
        jLabel9.setText("Identificación");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, -1, -1));

        txtIdentificacion.setForeground(new java.awt.Color(0, 0, 0));
        txtIdentificacion.setBorder(null);
        txtIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificacionKeyTyped(evt);
            }
        });
        jPanel1.add(txtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 180, -1));

        jLabel10.setForeground(new java.awt.Color(103, 160, 174));
        jLabel10.setText("Género");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, -1, -1));

        jLabel11.setForeground(new java.awt.Color(103, 160, 174));
        jLabel11.setText("Télefono");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, -1, -1));

        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono.setBorder(null);
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 180, -1));

        cboEspecialidades.setForeground(new java.awt.Color(0, 0, 0));
        cboEspecialidades.setBorder(null);
        cboEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEspecialidadesActionPerformed(evt);
            }
        });
        jPanel1.add(cboEspecialidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 180, 40));

        jLabel13.setForeground(new java.awt.Color(103, 160, 174));
        jLabel13.setText("Usuario - Correo");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, -1, -1));

        txtCorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreo.setBorder(null);
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 180, -1));

        btnEditar.setBackground(new java.awt.Color(103, 160, 174));
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar datos");
        btnEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 640, 130, 40));

        btnEliminar.setBackground(new java.awt.Color(103, 160, 174));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 700, 130, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 180, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 180, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 180, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 610, 180, 10));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 610, 180, 10));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 180, 10));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 180, 10));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 180, 10));

        btnRegistrarse.setBackground(new java.awt.Color(103, 160, 174));
        btnRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 640, 130, 40));

        btnLimpiar.setBackground(new java.awt.Color(103, 160, 174));
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 700, 130, 40));

        jPanel5.setBackground(new java.awt.Color(200, 230, 237));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 730, 414, -1));

        jLabel14.setForeground(new java.awt.Color(103, 160, 174));
        jLabel14.setText("Contraseña");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, -1, -1));

        txtContrasenia1.setForeground(new java.awt.Color(0, 0, 0));
        txtContrasenia1.setBorder(null);
        jPanel1.add(txtContrasenia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, 180, -1));

        jLabel15.setForeground(new java.awt.Color(103, 160, 174));
        jLabel15.setText("Hora inicio");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, -1, -1));

        cboGenero.setForeground(new java.awt.Color(0, 0, 0));
        cboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Masculino", "Femenino" }));
        cboGenero.setBorder(null);
        jPanel1.add(cboGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 180, 40));

        jLabel16.setForeground(new java.awt.Color(103, 160, 174));
        jLabel16.setText("Confirme su contraseña");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, -1, -1));

        lblVolver.setText("jLabel1");
        lblVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVolverMouseExited(evt);
            }
        });
        jPanel1.add(lblVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));

        lblRegresar.setBackground(new java.awt.Color(255, 255, 255));

        lblVolver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar_1.png"))); // NOI18N
        lblVolver1.setText("jLabel1");
        lblVolver1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVolver1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVolver1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVolver1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVolver1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout lblRegresarLayout = new javax.swing.GroupLayout(lblRegresar);
        lblRegresar.setLayout(lblRegresarLayout);
        lblRegresarLayout.setHorizontalGroup(
            lblRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblRegresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblVolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        lblRegresarLayout.setVerticalGroup(
            lblRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVolver1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btnVolverLayout = new javax.swing.GroupLayout(btnVolver);
        btnVolver.setLayout(btnVolverLayout);
        btnVolverLayout.setHorizontalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVolverLayout.createSequentialGroup()
                .addComponent(lblRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(380, Short.MAX_VALUE))
        );
        btnVolverLayout.setVerticalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVolverLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, 420, 40));

        jPanel6.setBackground(new java.awt.Color(200, 230, 237));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 770, 430, -1));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 540, 80, 20));

        cboFinMin.setForeground(new java.awt.Color(0, 0, 0));
        cboFinMin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "00", "30" }));
        jPanel1.add(cboFinMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 510, 80, 30));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, 80, 20));

        cboFinHora.setForeground(new java.awt.Color(0, 0, 0));
        cboFinHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "" }));
        jPanel1.add(cboFinHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, 80, 30));
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 80, 20));

        cboInicioHora.setForeground(new java.awt.Color(0, 0, 0));
        cboInicioHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "" }));
        jPanel1.add(cboInicioHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, 80, 30));
        jPanel1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, 80, 20));

        cboInicioMin.setForeground(new java.awt.Color(0, 0, 0));
        cboInicioMin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "00", "30" }));
        jPanel1.add(cboInicioMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 430, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseEntered
        exitBtn.setBackground(Color.red);
        lblCerrar.setForeground(Color.white);
    }//GEN-LAST:event_lblCerrarMouseEntered

    private void lblCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseExited
        exitBtn.setBackground(Color.white);
        lblCerrar.setForeground(Color.black);
    }//GEN-LAST:event_lblCerrarMouseExited

    private void barraLateralMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraLateralMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barraLateralMouseDragged

    private void barraLateralMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraLateralMousePressed
        xMouse = evt.getX();
        yMouse= evt.getY();
    }//GEN-LAST:event_barraLateralMousePressed

    private void txtIdBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdBuscarKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingresar solo números");
        }
    }//GEN-LAST:event_txtIdBuscarKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        if(txtIdBuscar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el numero de identificacion que desea buscar");
            return;
        }

        String identificacion = txtIdBuscar.getText();
        Medico medico = (Medico) controladorMedico.buscarMedicoIdentificacion(identificacion);

        if (medico != null) {
            txtNombres.setText(medico.getNombres());
            txtApellidos.setText(medico.getApellidos());
            txtEdad.setText(String.valueOf(medico.getEdad()));
            txtIdentificacion.setText(medico.getIdentificacion());
            cboGenero.setSelectedItem(medico.getGenero());
            cboEspecialidades.setSelectedItem(medico.getEspecializacion());
            cboInicioHora.setSelectedItem(String.valueOf(medico.getHoraInicio().getHour()));
            cboInicioMin.setSelectedItem(String.valueOf(medico.getHoraInicio().getMinute()));
            cboFinHora.setSelectedItem(String.valueOf(medico.getHoraFinal().getHour()));
            cboFinMin.setSelectedItem(String.valueOf(medico.getHoraFinal().getMinute()));
            txtTelefono.setText(medico.getNumTelefono());
            txtCorreo.setText(medico.getCorreo());
            txtContrasenia1.setText(medico.getContrasenia());
            txtConfirmarContrasenia.setText(medico.getContrasenia());
        } else {
            JOptionPane.showMessageDialog(null, "El Medico con numero de identificación: " + identificacion + " no se encuentra registrado");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingresar solo letras");
        }
    }//GEN-LAST:event_txtNombresKeyTyped

    private void txtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingresar solo letras");
        }
    }//GEN-LAST:event_txtApellidosKeyTyped

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingresar solo números");
        }
    }//GEN-LAST:event_txtEdadKeyTyped

    private void txtIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacionKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingresar solo números");
        }
    }//GEN-LAST:event_txtIdentificacionKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingresar solo números");
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void cboEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEspecialidadesActionPerformed

        if(cboEspecialidades.getSelectedItem().equals("Añadir Especialidad Nueva")){
            String especialidad = JOptionPane.showInputDialog(null, "Ingrese la nueva especialidad");

            if(especialidad!=null){
                boolean bien = controladorMedico.guardarEspecialidad(especialidad);
                if(bien){
                    actualizarComboBox();
                    cboEspecialidades.setSelectedItem(especialidad);
                }
            }
        }
    }//GEN-LAST:event_cboEspecialidadesActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(txtNombres.getText().isEmpty() || txtApellidos.getText().isEmpty() || txtIdentificacion.getText().isEmpty() || txtEdad.getText().isEmpty() || cboInicioHora.getSelectedIndex() == 0 || cboInicioMin.getSelectedIndex() == 0 || cboFinHora.getSelectedIndex() == 0 || cboFinMin.getSelectedIndex() == 0 || txtTelefono.getText().isEmpty() || cboGenero.getSelectedIndex() == 0 || cboEspecialidades.getSelectedIndex() == 0 || txtContrasenia1.getText().isEmpty() || txtCorreo.getText().isEmpty() || txtConfirmarContrasenia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Existen campos obligatorios por completar");
            return;
        }

        if(!txtContrasenia1.getText().equals(txtConfirmarContrasenia.getText())){
            JOptionPane.showMessageDialog( null , "Las contraseñas no coinciden");
            return;
        }
        
        if(cboInicioHora.getSelectedItem().equals(cboFinHora.getSelectedItem())  && cboInicioMin.getSelectedItem().equals(cboFinMin.getSelectedItem())){
            JOptionPane.showMessageDialog( null , "La hora de inicio, es la misma de salida, selecione otro horario");
            cboInicioHora.setSelectedIndex(0);
            cboFinHora.setSelectedIndex(0);
            cboInicioMin.setSelectedIndex(0);
            cboFinMin.setSelectedIndex(0);
            return;
        }

        String nombres = txtNombres.getText();
        String apellidos = txtApellidos.getText();
        int edad = Integer.parseInt(txtEdad.getText());
        String identificacion = txtIdentificacion.getText();
        String genero = String.valueOf(cboGenero.getSelectedItem());
        String especialidad = String.valueOf(cboEspecialidades.getSelectedItem());
        String telefono = txtTelefono.getText();
        String correo = txtCorreo.getText();
        String contrasenia = txtContrasenia1.getText();
        String rol = "Medico";

        int inicioHora1 = Integer.parseInt((String) cboInicioHora.getSelectedItem());
        int inicioMin1 = Integer.parseInt((String) cboInicioMin.getSelectedItem());

        int finalHora2 = Integer.parseInt((String) cboFinHora.getSelectedItem());
        int finalMin2 = Integer.parseInt((String) cboFinMin.getSelectedItem());

        LocalTime horaInicialFinal = LocalTime.of(inicioHora1, inicioMin1);
        LocalTime horaFinalalFinal = LocalTime.of(finalHora2, finalMin2);

        int  medida = controladorMedico.gererarMedida(horaInicialFinal, horaFinalalFinal);
        Medico medico = new Medico(controladorMedico.obtenerConsultas(identificacion), controladorMedico.obtenerCitas(identificacion), controladorMedico.obtenerDiaLibre(identificacion), especialidad, horaInicialFinal, horaFinalalFinal, medida, identificacion, nombres, apellidos, edad, genero, telefono, correo, contrasenia, rol);

        try{
            controladorMedico.editarMedico(medico);
            JOptionPane.showMessageDialog(null, "La informacion del medico " +nombres +" "+apellidos +  " ha sido actualizada");
            limpiarCampos();
            actualizarTabla();
        }catch(IdentificacionNoExisteException  | CorreoRegistradoException ex ){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (txtIdBuscar.getText().isEmpty()){
            JOptionPane.showMessageDialog( null , "Ingrese un numero de identificacion para buscar un medico y eliminar");
            return;
        }

        String identificacion = txtIdBuscar.getText();

        try{
            controladorMedico.eliminarMedico(identificacion);
            JOptionPane.showMessageDialog(null, "Medico eliminado correctamente");
            limpiarCampos();
            actualizarTabla();
        }catch(IdentificacionNoExisteException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        if(txtNombres.getText().isEmpty() || txtApellidos.getText().isEmpty() || txtIdentificacion.getText().isEmpty() || txtEdad.getText().isEmpty() || cboInicioHora.getSelectedIndex() == 0 || cboInicioMin.getSelectedIndex() == 0 || cboFinHora.getSelectedIndex() == 0 || cboFinMin.getSelectedIndex() == 0 ||txtTelefono.getText().isEmpty() || cboEspecialidades.getSelectedIndex() == 0 || cboGenero.getSelectedIndex() == 0 || txtContrasenia1.getText().isEmpty() || txtCorreo.getText().isEmpty() || txtConfirmarContrasenia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Existen campos obligatorios por completar");
            return;
        }

        if(!txtContrasenia1.getText().equals(txtConfirmarContrasenia.getText())){
            JOptionPane.showMessageDialog( null , "Las contraseñas no coinciden");
            return;
        }
        
        if(cboInicioHora.getSelectedItem().equals(cboFinHora.getSelectedItem())  && cboInicioMin.getSelectedItem().equals(cboFinMin.getSelectedItem())){
            JOptionPane.showMessageDialog( null , "La hora de inicio, es la misma de salida, selecione otro horario");
            cboInicioHora.setSelectedIndex(0);
            cboFinHora.setSelectedIndex(0);
            cboInicioMin.setSelectedIndex(0);
            cboFinMin.setSelectedIndex(0);
            return;
        }

        String nombres = txtNombres.getText();
        String apellidos = txtApellidos.getText();
        int edad = Integer.parseInt(txtEdad.getText());
        String identificacion = txtIdentificacion.getText();
        String genero = String.valueOf(cboGenero.getSelectedItem());
        String especialidad = String.valueOf(cboEspecialidades.getSelectedItem());
        String telefono = txtTelefono.getText();
        String correo = txtCorreo.getText();
        String contrasenia = txtContrasenia1.getText();
        String rol = "Medico";

        int inicioHora1 = Integer.parseInt((String) cboInicioHora.getSelectedItem());
        int inicioMin1 = Integer.parseInt((String) cboInicioMin.getSelectedItem());

        int finalHora2 = Integer.parseInt((String) cboFinHora.getSelectedItem());
        int finalMin2 = Integer.parseInt((String) cboFinMin.getSelectedItem());

        LocalTime horaInicioFinal = LocalTime.of(inicioHora1, inicioMin1);
        LocalTime horaFinalFinal = LocalTime.of(finalHora2, finalMin2);

        int  medida = controladorMedico.gererarMedida(horaInicioFinal, horaFinalFinal);
        Medico persona = new Medico(new ArrayList<> (), new ArrayList<> (), new ArrayList<> (), especialidad, horaInicioFinal, horaFinalFinal, medida, identificacion, nombres, apellidos, edad, genero, telefono, correo, contrasenia, rol);

        try{
            controladorMedico.guardarMedico(persona);
            JOptionPane.showMessageDialog(null, "El Médico " +nombres +" "+apellidos +  " ha sido agregado");
            limpiarCampos();
            actualizarTabla();
        }catch(RegistradoException  | CorreoRegistradoException | InformacionMedicoPacienteException ex ){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void lblVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseClicked
        this.dispose();
        JFrame v2 = new VentanaMenuAdmin(administrador);
        v2.setVisible(true);
    }//GEN-LAST:event_lblVolverMouseClicked

    private void lblVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseEntered
        lblRegresar.setBackground(Color.red);
        lblVolver.setForeground(Color.white);
    }//GEN-LAST:event_lblVolverMouseEntered

    private void lblVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseExited
        lblRegresar.setBackground(Color.white);
        lblVolver.setForeground(Color.black);
    }//GEN-LAST:event_lblVolverMouseExited

    private void lblVolver1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolver1MouseClicked
        this.dispose();
        JFrame v2 = new VentanaMenuAdmin(administrador);
        v2.setVisible(true);
    }//GEN-LAST:event_lblVolver1MouseClicked

    private void lblVolver1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolver1MouseEntered
        lblRegresar.setBackground(Color.red);
        lblVolver.setForeground(Color.white);
    }//GEN-LAST:event_lblVolver1MouseEntered

    private void lblVolver1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolver1MouseExited
        lblRegresar.setBackground(Color.white);
        lblVolver.setForeground(Color.black);
    }//GEN-LAST:event_lblVolver1MouseExited

    private void actualizarComboBox (){
        cboEspecialidades.removeAllItems();
        ArrayList<String> especialidades = controladorMedico.getEspecialidades();
        for (int i = 0; i < especialidades.size(); i++) {
            if(especialidades.get(i) != null){
                cboEspecialidades.addItem(especialidades.get(i));
            }
        }
        cboEspecialidades.setSelectedIndex(0);
    }
    
    private void actualizarTabla(){
        ArrayList<Medico> medicos = controladorMedico.obtenerMedicos();
        try{
            for (int i = 0; i < 3 ; i++) {
                for (int j = 0; j < modelo1.getRowCount(); j++) {
                    modelo1.removeRow(j);
                }
            }
        }catch(NullPointerException e){
        }
            try{
                for (int i = 0; i < medicos.size() ; i++) {
                    Medico aux = medicos.get(i);                   
                    Object[] ob = {aux.getNombres(), aux.getIdentificacion(), aux.getCorreo(), aux.getContrasenia()};
                    modelo1.addRow(ob);
                }
            }catch(NullPointerException e){        
            }
    }
    
    public void limpiarCampos() {
        txtNombres.setText(null);
        txtApellidos.setText(null);
        txtEdad.setText(null);
        txtIdentificacion.setText(null);
        cboGenero.setSelectedIndex(0);
        cboEspecialidades.setSelectedIndex(0);
        txtTelefono.setText(null);
        cboInicioHora.setSelectedIndex(0);
        cboInicioMin.setSelectedIndex(0);
        cboFinHora.setSelectedIndex(0);
        cboFinMin.setSelectedIndex(0);
        txtCorreo.setText(null);
        txtContrasenia1.setText(null);
        txtConfirmarContrasenia.setText(null);
        txtIdBuscar.setText(null);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraLateral;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JPanel btnVolver;
    private javax.swing.JComboBox<String> cboEspecialidades;
    private javax.swing.JComboBox<String> cboFinHora;
    private javax.swing.JComboBox<String> cboFinMin;
    private javax.swing.JComboBox<String> cboGenero;
    private javax.swing.JComboBox<String> cboInicioHora;
    private javax.swing.JComboBox<String> cboInicioMin;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JPanel lblRegresar;
    private javax.swing.JLabel lblVolver;
    private javax.swing.JLabel lblVolver1;
    private javax.swing.JTable tablaMedicos;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtConfirmarContrasenia;
    private javax.swing.JTextField txtContrasenia1;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtIdBuscar;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
