
package VistasAdminGeneral;

import Controladores.ControladorGestionPeticionesAdmin;
import Excepciones.NoExistePeticionException;
import Excepciones.PeticionCerradaException;
import Modelos.Consulta;
import Modelos.Paciente;
import Modelos.Persona;
import Modelos.Peticion;
import java.awt.Color;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diazje
 */
public class VentanaGestionPeticiones extends javax.swing.JFrame {

    
    int xMouse, yMouse;
    private Persona admin;
    DefaultTableModel modelo;
    private ControladorGestionPeticionesAdmin controladorGestionPeticiones;

    /**
     * Creates new form VentanaGestionPeticiones
     */
    public VentanaGestionPeticiones(Persona admin) {
        initComponents();
        this.admin = admin;
        modelo = (DefaultTableModel) tablaPeticiones.getModel();
        this.controladorGestionPeticiones = new ControladorGestionPeticionesAdmin();    
        actualizarTablaFecha();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        barraLateral = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        lblCerrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JPanel();
        lblRegresar = new javax.swing.JPanel();
        lblVolver = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPeticiones = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtConsultaCodigo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        txtConsultaFecha = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        txtConsultaMedico = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        txtConsultaHora = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        txtConsultaTipo = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        txtConsultaEstado = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        txtConsultaValoracion = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        txtConsultaNotas = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        txtConsultaMotivo = new javax.swing.JTextField();
        txtConsultaDiagnostico = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        btnLimpiarCampos = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        txtPeticionRespuestaPaciente = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtPeticionRespuestaAdmin = new javax.swing.JTextField();
        btnEnviarRespuesta = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtPeticionDetalle = new javax.swing.JTextField();
        txtPeticionCodigo = new javax.swing.JTextField();
        txtPeticionEstado = new javax.swing.JTextField();
        txtPeticionMotivo = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jPanel11 = new javax.swing.JPanel();
        txtPeticionFecha = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel36 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnTerminar = new javax.swing.JButton();
        btnPendientes = new javax.swing.JButton();
        btnTerminadas = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        txtUltimoMsg = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(103, 160, 174));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 10, 430));

        barraLateral.setBackground(new java.awt.Color(103, 160, 174));
        barraLateral.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraLateralMouseDragged(evt);
            }
        });
        barraLateral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraLateralMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(103, 160, 174));

        lblCerrar.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        lblCerrar.setForeground(new java.awt.Color(0, 0, 0));
        lblCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-cerrar-ventana-40.png"))); // NOI18N
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblCerrar))
        );

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(103, 160, 174));

        javax.swing.GroupLayout barraLateralLayout = new javax.swing.GroupLayout(barraLateral);
        barraLateral.setLayout(barraLateralLayout);
        barraLateralLayout.setHorizontalGroup(
            barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        barraLateralLayout.setVerticalGroup(
            barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraLateralLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraLateralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel1.add(barraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, -1));

        btnVolver.setBackground(new java.awt.Color(103, 160, 174));

        lblRegresar.setBackground(new java.awt.Color(103, 160, 174));

        lblVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar.png"))); // NOI18N
        lblVolver.setText("jLabel1");
        lblVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVolverMouseExited(evt);
            }
        });

        javax.swing.GroupLayout lblRegresarLayout = new javax.swing.GroupLayout(lblRegresar);
        lblRegresar.setLayout(lblRegresarLayout);
        lblRegresarLayout.setHorizontalGroup(
            lblRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblRegresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        lblRegresarLayout.setVerticalGroup(
            lblRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblRegresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblVolver))
        );

        javax.swing.GroupLayout btnVolverLayout = new javax.swing.GroupLayout(btnVolver);
        btnVolver.setLayout(btnVolverLayout);
        btnVolverLayout.setHorizontalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVolverLayout.createSequentialGroup()
                .addComponent(lblRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnVolverLayout.setVerticalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVolverLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 880, 970, -1));

        tablaPeticiones.setBackground(new java.awt.Color(255, 255, 255));
        tablaPeticiones.setForeground(new java.awt.Color(103, 160, 174));
        tablaPeticiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Fecha", "Paciente", "Medico", "Motivo", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPeticiones.setSelectionBackground(new java.awt.Color(103, 160, 174));
        tablaPeticiones.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tablaPeticiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPeticionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPeticiones);
        if (tablaPeticiones.getColumnModel().getColumnCount() > 0) {
            tablaPeticiones.getColumnModel().getColumn(0).setResizable(false);
            tablaPeticiones.getColumnModel().getColumn(1).setResizable(false);
            tablaPeticiones.getColumnModel().getColumn(2).setResizable(false);
            tablaPeticiones.getColumnModel().getColumn(3).setResizable(false);
            tablaPeticiones.getColumnModel().getColumn(4).setResizable(false);
            tablaPeticiones.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 554, 200));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo280_1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 262, 103));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(103, 160, 174));
        jLabel7.setText("Historial de peticiones");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, 30));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(103, 160, 174));
        jLabel8.setText("Seleccione una para ver la información");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, 30));

        txtConsultaCodigo.setEditable(false);
        txtConsultaCodigo.setForeground(new java.awt.Color(0, 0, 0));
        txtConsultaCodigo.setBorder(null);
        jPanel1.add(txtConsultaCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 150, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 150, 10));

        jLabel19.setForeground(new java.awt.Color(103, 160, 174));
        jLabel19.setText("Fecha consulta");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, -1, -1));

        txtConsultaFecha.setEditable(false);
        txtConsultaFecha.setForeground(new java.awt.Color(0, 0, 0));
        txtConsultaFecha.setBorder(null);
        jPanel1.add(txtConsultaFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 150, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 150, 10));

        jLabel20.setForeground(new java.awt.Color(103, 160, 174));
        jLabel20.setText("Medico");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, -1, -1));

        txtConsultaMedico.setEditable(false);
        txtConsultaMedico.setForeground(new java.awt.Color(0, 0, 0));
        txtConsultaMedico.setBorder(null);
        jPanel1.add(txtConsultaMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, 150, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 150, 10));

        jLabel21.setForeground(new java.awt.Color(103, 160, 174));
        jLabel21.setText("Hora consulta");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, -1, -1));

        txtConsultaHora.setEditable(false);
        txtConsultaHora.setForeground(new java.awt.Color(0, 0, 0));
        txtConsultaHora.setBorder(null);
        txtConsultaHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultaHoraActionPerformed(evt);
            }
        });
        jPanel1.add(txtConsultaHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, 150, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, 150, 10));

        jLabel22.setForeground(new java.awt.Color(103, 160, 174));
        jLabel22.setText("Tipo consulta");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));

        txtConsultaTipo.setEditable(false);
        txtConsultaTipo.setForeground(new java.awt.Color(0, 0, 0));
        txtConsultaTipo.setBorder(null);
        jPanel1.add(txtConsultaTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 150, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 150, 10));

        jLabel23.setForeground(new java.awt.Color(103, 160, 174));
        jLabel23.setText("Estado");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, -1, -1));

        txtConsultaEstado.setEditable(false);
        txtConsultaEstado.setForeground(new java.awt.Color(0, 0, 0));
        txtConsultaEstado.setBorder(null);
        jPanel1.add(txtConsultaEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 150, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, 150, 10));

        jLabel24.setForeground(new java.awt.Color(103, 160, 174));
        jLabel24.setText("Motivo");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, -1, -1));

        txtConsultaValoracion.setEditable(false);
        txtConsultaValoracion.setForeground(new java.awt.Color(0, 0, 0));
        txtConsultaValoracion.setBorder(null);
        jPanel1.add(txtConsultaValoracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 150, 40));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 150, 10));

        jLabel25.setForeground(new java.awt.Color(103, 160, 174));
        jLabel25.setText("Notas");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 270, -1, -1));

        txtConsultaNotas.setEditable(false);
        txtConsultaNotas.setForeground(new java.awt.Color(0, 0, 0));
        txtConsultaNotas.setBorder(null);
        jPanel1.add(txtConsultaNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, 150, 40));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 720, 200, 10));

        jLabel26.setForeground(new java.awt.Color(103, 160, 174));
        jLabel26.setText("Diagnostico");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, -1, -1));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, 150, 10));

        jLabel27.setForeground(new java.awt.Color(103, 160, 174));
        jLabel27.setText("Valoracion");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, -1, -1));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, 150, 10));

        txtConsultaMotivo.setEditable(false);
        txtConsultaMotivo.setForeground(new java.awt.Color(0, 0, 0));
        txtConsultaMotivo.setBorder(null);
        jPanel1.add(txtConsultaMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 150, 40));

        txtConsultaDiagnostico.setEditable(false);
        txtConsultaDiagnostico.setForeground(new java.awt.Color(0, 0, 0));
        txtConsultaDiagnostico.setBorder(null);
        jPanel1.add(txtConsultaDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 150, 40));

        jPanel9.setBackground(new java.awt.Color(103, 160, 174));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 970, 10));

        btnLimpiarCampos.setBackground(new java.awt.Color(103, 160, 174));
        btnLimpiarCampos.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarCampos.setText("Limpiar campos");
        btnLimpiarCampos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpiarCampos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiarCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 130, 40));

        jLabel28.setForeground(new java.awt.Color(103, 160, 174));
        jLabel28.setText("Codigo consulta");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, -1, -1));

        txtPeticionRespuestaPaciente.setEditable(false);
        txtPeticionRespuestaPaciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtPeticionRespuestaPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 560, 360, 50));

        jLabel29.setForeground(new java.awt.Color(103, 160, 174));
        jLabel29.setText("Responder");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 730, -1, -1));

        txtPeticionRespuestaAdmin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtPeticionRespuestaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 760, 360, 50));

        btnEnviarRespuesta.setBackground(new java.awt.Color(103, 160, 174));
        btnEnviarRespuesta.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarRespuesta.setText("Enviar");
        btnEnviarRespuesta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEnviarRespuesta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviarRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarRespuestaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnviarRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 830, 130, 40));

        jLabel30.setForeground(new java.awt.Color(103, 160, 174));
        jLabel30.setText("Respuesta del paciente");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 530, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(103, 160, 174));
        jLabel31.setText("Respuestas");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 480, -1, -1));

        txtPeticionDetalle.setEditable(false);
        txtPeticionDetalle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPeticionDetalle.setBorder(null);
        jPanel1.add(txtPeticionDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 660, 200, 60));

        txtPeticionCodigo.setEditable(false);
        txtPeticionCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPeticionCodigo.setBorder(null);
        jPanel1.add(txtPeticionCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 200, 30));

        txtPeticionEstado.setEditable(false);
        txtPeticionEstado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPeticionEstado.setBorder(null);
        jPanel1.add(txtPeticionEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 790, 200, 30));

        txtPeticionMotivo.setEditable(false);
        txtPeticionMotivo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPeticionMotivo.setBorder(null);
        jPanel1.add(txtPeticionMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 200, 60));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, 150, 10));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 200, 10));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 820, 200, 10));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 720, 200, 10));

        jPanel11.setBackground(new java.awt.Color(103, 160, 174));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 10, 420));

        txtPeticionFecha.setEditable(false);
        txtPeticionFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPeticionFecha.setBorder(null);
        jPanel1.add(txtPeticionFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 200, 30));
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 600, 200, 10));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(103, 160, 174));
        jLabel36.setText("Información de petición");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, -1, -1));

        jLabel32.setForeground(new java.awt.Color(103, 160, 174));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Codigo");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 540, 200, -1));

        jLabel33.setForeground(new java.awt.Color(103, 160, 174));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Fecha");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, 200, -1));

        jLabel34.setForeground(new java.awt.Color(103, 160, 174));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Motivo");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 200, -1));

        jLabel35.setForeground(new java.awt.Color(103, 160, 174));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Detalle");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 630, 200, -1));

        jLabel18.setForeground(new java.awt.Color(103, 160, 174));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Estado");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 760, 190, -1));

        btnTerminar.setBackground(new java.awt.Color(103, 160, 174));
        btnTerminar.setForeground(new java.awt.Color(255, 255, 255));
        btnTerminar.setText("Terminar");
        btnTerminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTerminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnTerminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 830, 130, 40));

        btnPendientes.setBackground(new java.awt.Color(103, 160, 174));
        btnPendientes.setForeground(new java.awt.Color(255, 255, 255));
        btnPendientes.setText("Ver pendientes");
        btnPendientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPendientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendientesActionPerformed(evt);
            }
        });
        jPanel1.add(btnPendientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 140, 40));

        btnTerminadas.setBackground(new java.awt.Color(103, 160, 174));
        btnTerminadas.setForeground(new java.awt.Color(255, 255, 255));
        btnTerminadas.setText("Ver terminadas");
        btnTerminadas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTerminadas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTerminadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminadasActionPerformed(evt);
            }
        });
        jPanel1.add(btnTerminadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 140, 40));

        jLabel37.setForeground(new java.awt.Color(103, 160, 174));
        jLabel37.setText("Mi último mensaje");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 630, -1, -1));

        txtUltimoMsg.setEditable(false);
        txtUltimoMsg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtUltimoMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 660, 360, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseEntered
        exitBtn.setBackground(Color.red);
        lblCerrar.setForeground(Color.white);
    }//GEN-LAST:event_lblCerrarMouseEntered

    private void lblCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseExited
        exitBtn.setBackground(new Color(103, 160,174));
        lblCerrar.setForeground(Color.black);
    }//GEN-LAST:event_lblCerrarMouseExited

    private void barraLateralMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraLateralMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barraLateralMouseDragged

    private void barraLateralMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraLateralMousePressed
        xMouse = evt.getX();
        yMouse= evt.getY();
    }//GEN-LAST:event_barraLateralMousePressed

    private void lblVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseClicked
        this.dispose();
        JFrame v2 = new VentanaMenuAdmin(admin);
        v2.setVisible(true);
    }//GEN-LAST:event_lblVolverMouseClicked

    private void lblVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseEntered
        lblRegresar.setBackground(Color.red);
        lblVolver.setForeground(Color.white);
    }//GEN-LAST:event_lblVolverMouseEntered

    private void lblVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseExited
        lblRegresar.setBackground(new Color(103, 160,174));
        lblVolver.setForeground(Color.black);
    }//GEN-LAST:event_lblVolverMouseExited

    private void tablaPeticionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPeticionesMouseClicked

        int fila = tablaPeticiones.getSelectedRow();
        String codigo =  tablaPeticiones.getValueAt(fila, 0).toString();

        Peticion peticion = controladorGestionPeticiones.buscarPeticion(codigo);

        txtConsultaCodigo.setText(peticion.getConsulta().getCodigo());
        txtConsultaMedico.setText(peticion.getConsulta().getMedico().getNombres() + " " + peticion.getConsulta().getMedico().getApellidos());
        txtConsultaFecha.setText(peticion.getConsulta().getFechaAtencion().toString());
        txtConsultaHora.setText(peticion.getConsulta().getHora().toString());
        txtConsultaTipo.setText(peticion.getConsulta().getTipoConsulta());
        txtConsultaEstado.setText(peticion.getConsulta().getEstado());
        txtConsultaMotivo.setText(peticion.getConsulta().getMotivo());
        txtConsultaNotas.setText(peticion.getConsulta().getNotas());
        txtConsultaDiagnostico.setText(peticion.getConsulta().getDiagnostico());
        txtConsultaValoracion.setText(peticion.getConsulta().getValoracion());
        txtPeticionRespuestaPaciente.setText(peticion.getRespPaciente());
        txtPeticionCodigo.setText(peticion.getCodigo());
        txtPeticionEstado.setText(peticion.getEstado());
        txtPeticionFecha.setText(peticion.getFechaCreacion().toString());
        txtPeticionDetalle.setText(peticion.getDetallePQRS());
        txtPeticionMotivo.setText(peticion.getMotivoAtencion());
        txtUltimoMsg.setText(peticion.getRespAdmin());
    }//GEN-LAST:event_tablaPeticionesMouseClicked

    private void txtConsultaHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultaHoraActionPerformed
    }//GEN-LAST:event_txtConsultaHoraActionPerformed

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarCamposActionPerformed

    private void btnEnviarRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarRespuestaActionPerformed
        if(txtPeticionCodigo.getText().isEmpty() || txtPeticionRespuestaAdmin.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Falta información para enviar la peticion");
        }else {
            String codigo = txtPeticionCodigo.getText();
            Consulta consulta1 = controladorGestionPeticiones.buscarConsulta(codigo);
            Peticion peticion1 = controladorGestionPeticiones.buscarPeticion(codigo);
            String respAdmin = txtPeticionRespuestaAdmin.getText();

            String estado = "En progreso";
            Peticion peticion = new Peticion(consulta1, codigo, peticion1.getMotivoAtencion(), peticion1.getFechaCreacion(), peticion1.getDetallePQRS(), estado, respAdmin, peticion1.getRespPaciente());
            
            try{
                controladorGestionPeticiones.actulizarPeticion(peticion);
                JOptionPane.showMessageDialog(null, "Cita peticion se ha respondido correctamente");
                limpiarCampos();
                actualizarTablaFecha();
            }catch(NoExistePeticionException | PeticionCerradaException ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
                limpiarCampos();
            }        
        }  
    }//GEN-LAST:event_btnEnviarRespuestaActionPerformed

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed

        if(txtPeticionCodigo.getText().isEmpty() || txtPeticionRespuestaAdmin.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Falta información para enviar la peticion");
        }else {
          String codigo = txtPeticionCodigo.getText();
            Consulta consulta1 = controladorGestionPeticiones.buscarConsulta(codigo);
            Peticion peticion1 = controladorGestionPeticiones.buscarPeticion(codigo);
            String respAdmin = txtPeticionRespuestaAdmin.getText();
            String respPaciente = txtPeticionRespuestaPaciente.getText();
            String estado = "Cerrado";
        
            Peticion peticion = new Peticion(consulta1, codigo, peticion1.getMotivoAtencion(), peticion1.getFechaCreacion(), peticion1.getDetallePQRS(), estado, respAdmin, peticion1.getRespPaciente());
        
            try{
                controladorGestionPeticiones.actulizarPeticion(peticion);
                JOptionPane.showMessageDialog(null, "Cita peticion se ha respondido correctamente y ha sido terminada");
                actualizarTablaFecha();
                limpiarCampos();               
            }catch(NoExistePeticionException | PeticionCerradaException ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
                actualizarTablaFecha();
                limpiarCampos();
            }  
        }
    }//GEN-LAST:event_btnTerminarActionPerformed

    private void btnPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendientesActionPerformed
        actualizarTablaFecha();
    }//GEN-LAST:event_btnPendientesActionPerformed

    private void btnTerminadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminadasActionPerformed
        actualizarTablaTerminadas();
    }//GEN-LAST:event_btnTerminadasActionPerformed

    public void limpiarCampos() {
        txtConsultaCodigo.setText(null);
        txtConsultaMedico.setText(null);
        txtConsultaFecha.setText(null);
        txtConsultaHora.setText(null);   
        txtConsultaTipo.setText(null);
        txtConsultaEstado.setText(null);
        txtConsultaMotivo.setText(null);
        txtConsultaNotas.setText(null);
        txtConsultaDiagnostico.setText(null);
        txtConsultaValoracion.setText(null);
        txtPeticionRespuestaAdmin.setText(null);
        txtPeticionRespuestaPaciente.setText(null);
        txtPeticionCodigo.setText(null);
        txtPeticionDetalle.setText(null);
        txtPeticionEstado.setText(null);
        txtPeticionFecha.setText(null);
        txtPeticionMotivo.setText(null);
        txtUltimoMsg.setText(null);
    }
    
    public void actualizarTablaFecha(){
             
        ArrayList<Peticion> peticiones = controladorGestionPeticiones.conseguirPeticiones();
        
        try{
            for (int i = 0; i < 3 ; i++) {
                for (int j = 0; j < modelo.getRowCount(); j++) {
                    modelo.removeRow(j);
                }
            }
        }catch(NullPointerException e){
        }
            try{
                for (int i = 0; i < peticiones.size() ; i++) {                    
                    Peticion aux = peticiones.get(i);
                    Object[] ob = {aux.getCodigo(), aux.getFechaCreacion(), aux.getConsulta().getPaciente().getNombres() + " " + aux.getConsulta().getPaciente().getApellidos(), aux.getConsulta().getMedico().getNombres() + " " + aux.getConsulta().getMedico().getApellidos(), aux.getMotivoAtencion(), aux.getEstado()};
                    modelo.addRow(ob);              
                }
            }catch(NullPointerException e){        
        } 
    }
    
    public void actualizarTablaTerminadas(){
             
        ArrayList<Peticion> peticiones = controladorGestionPeticiones.conseguirPeticionesTerminadas();
        
        try{
            for (int i = 0; i < 3 ; i++) {
                for (int j = 0; j < modelo.getRowCount(); j++) {
                    modelo.removeRow(j);
                }
            }
        }catch(NullPointerException e){
        }
            try{
                for (int i = 0; i < peticiones.size() ; i++) {                    
                    Peticion aux = peticiones.get(i);
                    Object[] ob = {aux.getCodigo(), aux.getFechaCreacion(), aux.getConsulta().getPaciente().getNombres() + " " + aux.getConsulta().getPaciente().getApellidos(), aux.getConsulta().getMedico().getNombres() + " " + aux.getConsulta().getMedico().getApellidos(), aux.getMotivoAtencion(), aux.getEstado()};
                    modelo.addRow(ob);              
                }
            }catch(NullPointerException e){        
        } 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionPeticiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionPeticiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionPeticiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionPeticiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraLateral;
    private javax.swing.JButton btnEnviarRespuesta;
    private javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JButton btnPendientes;
    private javax.swing.JButton btnTerminadas;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JPanel btnVolver;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JPanel lblRegresar;
    private javax.swing.JLabel lblVolver;
    private javax.swing.JTable tablaPeticiones;
    private javax.swing.JTextField txtConsultaCodigo;
    private javax.swing.JTextField txtConsultaDiagnostico;
    private javax.swing.JTextField txtConsultaEstado;
    private javax.swing.JTextField txtConsultaFecha;
    private javax.swing.JTextField txtConsultaHora;
    private javax.swing.JTextField txtConsultaMedico;
    private javax.swing.JTextField txtConsultaMotivo;
    private javax.swing.JTextField txtConsultaNotas;
    private javax.swing.JTextField txtConsultaTipo;
    private javax.swing.JTextField txtConsultaValoracion;
    private javax.swing.JTextField txtPeticionCodigo;
    private javax.swing.JTextField txtPeticionDetalle;
    private javax.swing.JTextField txtPeticionEstado;
    private javax.swing.JTextField txtPeticionFecha;
    private javax.swing.JTextField txtPeticionMotivo;
    private javax.swing.JTextField txtPeticionRespuestaAdmin;
    private javax.swing.JTextField txtPeticionRespuestaPaciente;
    private javax.swing.JTextField txtUltimoMsg;
    // End of variables declaration//GEN-END:variables
}
