
package VistasAdminGeneral;

import Controladores.ControladorHistorialMedicosFiltro;
import static Controladores.ControladorHistorialMedicosFiltro.obtenerMedicoMasConsultas;
import static Controladores.ControladorHistorialMedicosFiltro.obtenerPacientesMasConsultas;
import Modelos.Consulta;
import Modelos.ConsultaInfo;
import Modelos.ConsultaInfoPaciente;
import Modelos.Medico;
import Modelos.Persona;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diazje
 */
public class VentanaHistorialConsultasMedico extends javax.swing.JFrame {

    private Persona administrador;
    DefaultTableModel modelo;
    DefaultTableModel modelo2;
    int xMouse, yMouse;
    private ControladorHistorialMedicosFiltro controladorMedicoFiltro;
    
    public VentanaHistorialConsultasMedico(Persona administrador) {
        initComponents();
        modelo = (DefaultTableModel) tablaAtenciones.getModel();
        modelo2 = (DefaultTableModel) tablaMedicos.getModel();
        this.administrador = administrador;
        this.controladorMedicoFiltro = new ControladorHistorialMedicosFiltro();
        actualizarEspecialidades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barraLateral = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        lblCerrar = new javax.swing.JLabel();
        btnVolver2 = new javax.swing.JPanel();
        lblRegresar2 = new javax.swing.JPanel();
        lblVolver2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAtenciones = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cboEspecialidades = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMedicos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnMedicosConsultas = new javax.swing.JButton();
        dateFechaInicial = new com.toedter.calendar.JDateChooser();
        dateFechaFinal = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnPacientesConsultas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraLateral.setBackground(new java.awt.Color(103, 160, 174));
        barraLateral.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraLateralMouseDragged(evt);
            }
        });
        barraLateral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraLateralMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(103, 160, 174));
        exitBtn.setForeground(new java.awt.Color(103, 160, 174));

        lblCerrar.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        lblCerrar.setForeground(new java.awt.Color(0, 0, 0));
        lblCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-cerrar-ventana-40.png"))); // NOI18N
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblCerrar))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblCerrar))
        );

        javax.swing.GroupLayout barraLateralLayout = new javax.swing.GroupLayout(barraLateral);
        barraLateral.setLayout(barraLateralLayout);
        barraLateralLayout.setHorizontalGroup(
            barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraLateralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        barraLateralLayout.setVerticalGroup(
            barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraLateralLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(barraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 40));

        btnVolver2.setBackground(new java.awt.Color(103, 160, 174));

        lblRegresar2.setBackground(new java.awt.Color(103, 160, 174));

        lblVolver2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar.png"))); // NOI18N
        lblVolver2.setText("jLabel1");
        lblVolver2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVolver2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVolver2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVolver2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVolver2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout lblRegresar2Layout = new javax.swing.GroupLayout(lblRegresar2);
        lblRegresar2.setLayout(lblRegresar2Layout);
        lblRegresar2Layout.setHorizontalGroup(
            lblRegresar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblRegresar2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblVolver2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        lblRegresar2Layout.setVerticalGroup(
            lblRegresar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblRegresar2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblVolver2))
        );

        javax.swing.GroupLayout btnVolver2Layout = new javax.swing.GroupLayout(btnVolver2);
        btnVolver2.setLayout(btnVolver2Layout);
        btnVolver2Layout.setHorizontalGroup(
            btnVolver2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVolver2Layout.createSequentialGroup()
                .addComponent(lblRegresar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnVolver2Layout.setVerticalGroup(
            btnVolver2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVolver2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblRegresar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnVolver2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 860, 810, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo280_1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 275, 99));

        tablaAtenciones.setBackground(new java.awt.Color(255, 255, 255));
        tablaAtenciones.setForeground(new java.awt.Color(103, 160, 174));
        tablaAtenciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Paciente", "Motivo", "Diagnostico", "Valoración"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaAtenciones.setSelectionBackground(new java.awt.Color(103, 160, 174));
        tablaAtenciones.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tablaAtenciones);
        if (tablaAtenciones.getColumnModel().getColumnCount() > 0) {
            tablaAtenciones.getColumnModel().getColumn(0).setResizable(false);
            tablaAtenciones.getColumnModel().getColumn(1).setResizable(false);
            tablaAtenciones.getColumnModel().getColumn(2).setResizable(false);
            tablaAtenciones.getColumnModel().getColumn(3).setResizable(false);
            tablaAtenciones.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, 660, 170));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 33)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(103, 160, 174));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Atenciones realizadas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 580, -1));

        cboEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEspecialidadesActionPerformed(evt);
            }
        });
        jPanel1.add(cboEspecialidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 190, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(103, 160, 174));
        jLabel4.setText("Seleccione la especialidad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        tablaMedicos.setBackground(new java.awt.Color(255, 255, 255));
        tablaMedicos.setForeground(new java.awt.Color(103, 160, 174));
        tablaMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Medico"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaMedicos.setSelectionBackground(new java.awt.Color(103, 160, 174));
        tablaMedicos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tablaMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMedicosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaMedicos);
        if (tablaMedicos.getColumnModel().getColumnCount() > 0) {
            tablaMedicos.getColumnModel().getColumn(0).setResizable(false);
            tablaMedicos.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 510, 140));

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 33)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(103, 160, 174));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Atenciones realizadas por médicos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 580, -1));

        jLabel6.setForeground(new java.awt.Color(103, 160, 174));
        jLabel6.setText("Seleccione la segunda fecha");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 720, -1, -1));

        btnMedicosConsultas.setBackground(new java.awt.Color(103, 160, 174));
        btnMedicosConsultas.setForeground(new java.awt.Color(255, 255, 255));
        btnMedicosConsultas.setText("Ver medico con mas consultas");
        btnMedicosConsultas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMedicosConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicosConsultasActionPerformed(evt);
            }
        });
        jPanel1.add(btnMedicosConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 800, 230, 40));
        jPanel1.add(dateFechaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 750, 180, -1));
        jPanel1.add(dateFechaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 750, 190, -1));

        jLabel7.setForeground(new java.awt.Color(103, 160, 174));
        jLabel7.setText("Seleccione el médico parar consultar su historial");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        jLabel8.setForeground(new java.awt.Color(103, 160, 174));
        jLabel8.setText("Seleccione la primera fecha");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 720, -1, -1));

        btnPacientesConsultas.setBackground(new java.awt.Color(103, 160, 174));
        btnPacientesConsultas.setForeground(new java.awt.Color(255, 255, 255));
        btnPacientesConsultas.setText("Ver pacientes + consultas");
        btnPacientesConsultas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPacientesConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacientesConsultasActionPerformed(evt);
            }
        });
        jPanel1.add(btnPacientesConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 800, 230, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseEntered
        exitBtn.setBackground(Color.red);
        lblCerrar.setForeground(Color.white);
    }//GEN-LAST:event_lblCerrarMouseEntered

    private void lblCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseExited
        exitBtn.setBackground(new Color(103, 160,174));
        lblCerrar.setForeground(Color.black);
    }//GEN-LAST:event_lblCerrarMouseExited

    private void barraLateralMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraLateralMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barraLateralMouseDragged

    private void barraLateralMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraLateralMousePressed
        xMouse = evt.getX();
        yMouse= evt.getY();
    }//GEN-LAST:event_barraLateralMousePressed

    private void lblVolver2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolver2MouseClicked
        this.dispose();
        JFrame v2 = new VentanaMenuAdmin(administrador);
        v2.setVisible(true);
    }//GEN-LAST:event_lblVolver2MouseClicked

    private void lblVolver2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolver2MouseEntered
        lblRegresar2.setBackground(Color.red);
        lblVolver2.setForeground(Color.white);
    }//GEN-LAST:event_lblVolver2MouseEntered

    private void lblVolver2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolver2MouseExited
        lblRegresar2.setBackground(new Color(103, 160,174));
        lblVolver2.setForeground(Color.black);
    }//GEN-LAST:event_lblVolver2MouseExited

    private void cboEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEspecialidadesActionPerformed
        String especialidad = (String) cboEspecialidades.getSelectedItem();
        actualizarTablaMedicos(especialidad);
    }//GEN-LAST:event_cboEspecialidadesActionPerformed

    private void tablaMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMedicosMouseClicked
        int row = tablaMedicos.getSelectedRow();
        String identificacion =  tablaMedicos.getValueAt(row, 0).toString();

        actualizarTablaAtenciones(identificacion);
    }//GEN-LAST:event_tablaMedicosMouseClicked

    private void btnMedicosConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicosConsultasActionPerformed
        if(dateFechaInicial.getDate() == null || dateFechaFinal.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Seleccione el rango que desea buscar");
        }else {
            Date xInicio = dateFechaInicial.getDate();
            Date xFinal = dateFechaFinal.getDate();
            LocalDate fechaInicio = new java.sql.Date(xInicio.getTime()).toLocalDate();
            LocalDate fechaFin = new java.sql.Date(xFinal.getTime()).toLocalDate();
            ArrayList<Consulta> consultas = Singleton.PersonaSingleton.getInstancia().getConsultas();
            ConsultaInfo consultaInfo = obtenerMedicoMasConsultas(consultas, fechaInicio, fechaFin);
         
            if (consultaInfo != null) {
            JOptionPane.showMessageDialog(null, "Médico con más consultas en el periodo: " + consultaInfo.getMedico().getNombres() + consultaInfo.getMedico().getApellidos()
                    + "\n La cantidad de consultas total es de: "+consultaInfo.getCantidad());
                    limpiarCampos();
            }else {
            JOptionPane.showMessageDialog(null, "No hay consultas registradas en el periodo indicado.");
            }
        } 
    }//GEN-LAST:event_btnMedicosConsultasActionPerformed

    private void btnPacientesConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacientesConsultasActionPerformed
        if(dateFechaInicial.getDate() == null || dateFechaFinal.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Seleccione el rango que desea buscar");
        }else {
            Date xInicio = dateFechaInicial.getDate();
            Date xFinal = dateFechaFinal.getDate();
            LocalDate fechaInicio = new java.sql.Date(xInicio.getTime()).toLocalDate();
            LocalDate fechaFin = new java.sql.Date(xFinal.getTime()).toLocalDate();
            ArrayList<Consulta> consultas = Singleton.PersonaSingleton.getInstancia().getConsultas();
            List<ConsultaInfoPaciente> pacientesInfo = obtenerPacientesMasConsultas(consultas, fechaInicio, fechaFin, 3);
            
            StringBuilder message = new StringBuilder("Pacientes que más han ido a consulta en el periodo:\n");
            message.append("Fecha de inicio: ").append(fechaInicio).append(" hasta - fecha final: ").append(fechaFin).append("\n\n");
    
            for (ConsultaInfoPaciente pacienteInfo : pacientesInfo) {
//            JOptionPane.showMessageDialog(null, " Pacientes que más han ido a consulta en el periodo: "
//                + "\n " + "fecha de inicio: " + fechaInicio + " hasta - fecha final: " + fechaFin
//                + "\n Paciente: "+ pacienteInfo.getPaciente().getNombres() + " " + pacienteInfo.getPaciente().getApellidos()
//                + "\n Cantidad de consultas realizadas: " + pacienteInfo.getCantidad());
            message.append("Paciente: ").append(pacienteInfo.getPaciente().getNombres()).append(" ").append(pacienteInfo.getPaciente().getApellidos()).append("\n");
            message.append("Cantidad de consultas realizadas: ").append(pacienteInfo.getCantidad()).append("\n");
            message.append("Identificación: ").append(pacienteInfo.getPaciente().getIdentificacion()).append("\n");
            message.append("Edad: ").append(pacienteInfo.getPaciente().getEdad()).append("\n");
            message.append("Teléfono: ").append(pacienteInfo.getPaciente().getNumTelefono()).append("\n\n");
            }  
            JOptionPane.showMessageDialog(null, message.toString());
        } 
    }//GEN-LAST:event_btnPacientesConsultasActionPerformed

    public void limpiarCampos(){
        dateFechaFinal.setDate(null);
        dateFechaInicial.setDate(null);
    }
    
    public void actualizarEspecialidades(){
        cboEspecialidades.removeAllItems();
        ArrayList<String> especialidades = controladorMedicoFiltro.getEspecialidades();
        for (int i = 0; i < especialidades.size(); i++) {
            if(especialidades.get(i) != null){
                if(!especialidades.get(i).equals("Añadir Especialidad Nueva") && !especialidades.get(i).equals("-Elegir-")){
                    cboEspecialidades.addItem(especialidades.get(i));
                }
            }
        }
        cboEspecialidades.setSelectedIndex(-1);
    }

    public void actualizarTablaAtenciones(String identificacion){
        
        Medico medico = (Medico) controladorMedicoFiltro.buscarMedicoIdentificacion(identificacion);
        ArrayList<Consulta> consultas = controladorMedicoFiltro.conseguirConsultas(medico);
        
        try{
            for (int i = 0; i < 3 ; i++) {
                for (int j = 0; j < modelo.getRowCount(); j++) {
                    modelo.removeRow(j);
                }
            }
        }catch(NullPointerException e){
        }
            try{
                for (int i = 0; i < consultas.size() ; i++) {                    
                      Consulta aux = consultas.get(i);
                      Object[] ob = {aux.getFechaAtencion(), aux.getPaciente().getNombres() + " " +aux.getPaciente().getApellidos(), aux.getMotivo(), aux.getDiagnostico(), aux.getValoracion() };
                      modelo.addRow(ob);                     
                }
            }catch(NullPointerException e){        
        } 
    }
    
    public void actualizarTablaMedicos(String especialidad){    
        ArrayList<Medico> medicos = controladorMedicoFiltro.obtenerMedicos(especialidad);
        try{
            for (int i = 0; i < 3 ; i++) {
                for (int j = 0; j < modelo2.getRowCount(); j++) {
                    modelo2.removeRow(j);
                }
            }
        }catch(NullPointerException e){
        }
            try{
                for (int i = 0; i < medicos.size() ; i++) {
                      Medico aux = medicos.get(i);
                      Object[] ob = {aux.getIdentificacion(), aux.getNombres()+" " + aux.getApellidos()};
                      modelo2.addRow(ob);                     
                    }
            }catch(NullPointerException e){        
        } 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorialConsultasMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorialConsultasMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorialConsultasMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorialConsultasMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraLateral;
    private javax.swing.JButton btnMedicosConsultas;
    private javax.swing.JButton btnPacientesConsultas;
    private javax.swing.JPanel btnVolver2;
    private javax.swing.JComboBox<String> cboEspecialidades;
    private com.toedter.calendar.JDateChooser dateFechaFinal;
    private com.toedter.calendar.JDateChooser dateFechaInicial;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JPanel lblRegresar2;
    private javax.swing.JLabel lblVolver2;
    private javax.swing.JTable tablaAtenciones;
    private javax.swing.JTable tablaMedicos;
    // End of variables declaration//GEN-END:variables
}
