
package VistasMedico;

import Controladores.ControladorGestionarCitas;
import Excepciones.CitaAtendidaException;
import Modelos.Consulta;
import Modelos.Medico;
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diazje
 */
public class VentanaGestionCita extends javax.swing.JFrame {

    int xMouse, yMouse;
    private Medico medico;
    DefaultTableModel modelo;
    private ControladorGestionarCitas controladorCitas;

    
    /**
     * Creates new form VentanaGestionCitas
     */
    public VentanaGestionCita(Medico medico) {
        initComponents();
        this.medico = medico;
        modelo = (DefaultTableModel) tablaConsultas.getModel();
        this.controladorCitas = new ControladorGestionarCitas();
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barraLateral = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        lblCerrar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaConsultas = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JPanel();
        lblRegresar = new javax.swing.JPanel();
        lblVolver = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPaciente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtCodigo = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnLimpiarCampos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtValoracion = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txtNombrePaciente = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txtIdentificacionPaciente = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        txtTelefono = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        txtApellidoPaciente = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        txtGenero = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        txtEps = new javax.swing.JTextField();
        btnAtender = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        txtNotas = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtDiagnostico = new javax.swing.JTextField();
        btnHistorialMedico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraLateral.setBackground(new java.awt.Color(255, 255, 255));
        barraLateral.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraLateralMouseDragged(evt);
            }
        });
        barraLateral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraLateralMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        lblCerrar.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        lblCerrar.setForeground(new java.awt.Color(0, 0, 0));
        lblCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-cerrar-ventana-40.png"))); // NOI18N
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblCerrar))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblCerrar))
        );

        javax.swing.GroupLayout barraLateralLayout = new javax.swing.GroupLayout(barraLateral);
        barraLateral.setLayout(barraLateralLayout);
        barraLateralLayout.setHorizontalGroup(
            barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraLateralLayout.createSequentialGroup()
                .addContainerGap(1070, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        barraLateralLayout.setVerticalGroup(
            barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraLateralLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(barraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 40));

        tablaConsultas.setBackground(new java.awt.Color(255, 255, 255));
        tablaConsultas.setForeground(new java.awt.Color(103, 160, 174));
        tablaConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Paciente", "Fecha", "Hora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaConsultas.setSelectionBackground(new java.awt.Color(103, 160, 174));
        tablaConsultas.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tablaConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaConsultasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaConsultas);
        if (tablaConsultas.getColumnModel().getColumnCount() > 0) {
            tablaConsultas.getColumnModel().getColumn(0).setResizable(false);
            tablaConsultas.getColumnModel().getColumn(1).setResizable(false);
            tablaConsultas.getColumnModel().getColumn(2).setResizable(false);
            tablaConsultas.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 400, 420));

        jPanel7.setBackground(new java.awt.Color(103, 160, 174));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1110, -1));

        btnVolver.setBackground(new java.awt.Color(103, 160, 174));

        lblRegresar.setBackground(new java.awt.Color(103, 160, 174));

        lblVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar.png"))); // NOI18N
        lblVolver.setText("jLabel1");
        lblVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVolverMouseExited(evt);
            }
        });

        javax.swing.GroupLayout lblRegresarLayout = new javax.swing.GroupLayout(lblRegresar);
        lblRegresar.setLayout(lblRegresarLayout);
        lblRegresarLayout.setHorizontalGroup(
            lblRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblRegresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        lblRegresarLayout.setVerticalGroup(
            lblRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblRegresarLayout.createSequentialGroup()
                .addComponent(lblVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout btnVolverLayout = new javax.swing.GroupLayout(btnVolver);
        btnVolver.setLayout(btnVolverLayout);
        btnVolverLayout.setHorizontalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVolverLayout.createSequentialGroup()
                .addComponent(lblRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1070, Short.MAX_VALUE))
        );
        btnVolverLayout.setVerticalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVolverLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, 1110, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(103, 160, 174));
        jLabel3.setText("Consultas pendientes");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        txtPaciente.setEditable(false);
        txtPaciente.setForeground(new java.awt.Color(0, 0, 0));
        txtPaciente.setBorder(null);
        jPanel1.add(txtPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 150, -1));

        jLabel7.setForeground(new java.awt.Color(103, 160, 174));
        jLabel7.setText("Codigo de consulta");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 150, 10));

        txtCodigo.setEditable(false);
        txtCodigo.setForeground(new java.awt.Color(0, 0, 0));
        txtCodigo.setBorder(null);
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 150, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 150, 10));

        jLabel8.setForeground(new java.awt.Color(103, 160, 174));
        jLabel8.setText("Télefono");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 570, -1, -1));

        txtHora.setEditable(false);
        txtHora.setForeground(new java.awt.Color(0, 0, 0));
        txtHora.setBorder(null);
        jPanel1.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 150, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 150, 10));

        jLabel9.setForeground(new java.awt.Color(103, 160, 174));
        jLabel9.setText("Motivo de consulta");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, -1, -1));

        txtMotivo.setEditable(false);
        txtMotivo.setForeground(new java.awt.Color(0, 0, 0));
        txtMotivo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMotivo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 230, 40));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 150, 10));

        jLabel10.setForeground(new java.awt.Color(103, 160, 174));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Seleccione una consulta para ver su información");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 390, -1));

        txtFecha.setEditable(false);
        txtFecha.setForeground(new java.awt.Color(0, 0, 0));
        txtFecha.setBorder(null);
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 150, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(103, 160, 174));
        jLabel11.setText("Información del paciente");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, -1, -1));

        btnLimpiarCampos.setBackground(new java.awt.Color(103, 160, 174));
        btnLimpiarCampos.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarCampos.setText("Limpiar campos");
        btnLimpiarCampos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpiarCampos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiarCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 680, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo280_1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 270, 80));

        jLabel14.setForeground(new java.awt.Color(103, 160, 174));
        jLabel14.setText("Fecha");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, -1, -1));

        jPanel8.setBackground(new java.awt.Color(103, 160, 174));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 10, 720));

        jLabel15.setForeground(new java.awt.Color(103, 160, 174));
        jLabel15.setText("Paciente");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(103, 160, 174));
        jLabel16.setText("Información de la consulta");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        jLabel17.setForeground(new java.awt.Color(103, 160, 174));
        jLabel17.setText("Hora");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        jLabel18.setForeground(new java.awt.Color(103, 160, 174));
        jLabel18.setText("Nombres");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, -1, -1));

        jLabel19.setForeground(new java.awt.Color(103, 160, 174));
        jLabel19.setText("Apellidos");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, -1, -1));

        jLabel20.setForeground(new java.awt.Color(103, 160, 174));
        jLabel20.setText("Identificación");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, -1, -1));

        jLabel21.setForeground(new java.awt.Color(103, 160, 174));
        jLabel21.setText("Género");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, -1, -1));

        jLabel22.setForeground(new java.awt.Color(103, 160, 174));
        jLabel22.setText("EPS");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 570, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(103, 160, 174));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Atender consulta");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(852, 100, 240, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(103, 160, 174));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Valoración");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 460, 240, -1));

        txtValoracion.setForeground(new java.awt.Color(0, 0, 0));
        txtValoracion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtValoracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 500, 190, 60));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 150, 10));

        txtNombrePaciente.setEditable(false);
        txtNombrePaciente.setForeground(new java.awt.Color(0, 0, 0));
        txtNombrePaciente.setBorder(null);
        jPanel1.add(txtNombrePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, 150, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 550, 150, 10));

        txtIdentificacionPaciente.setEditable(false);
        txtIdentificacionPaciente.setForeground(new java.awt.Color(0, 0, 0));
        txtIdentificacionPaciente.setBorder(null);
        jPanel1.add(txtIdentificacionPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 150, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 620, 150, 10));

        txtTelefono.setEditable(false);
        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono.setBorder(null);
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 600, 150, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 150, 10));

        txtApellidoPaciente.setEditable(false);
        txtApellidoPaciente.setForeground(new java.awt.Color(0, 0, 0));
        txtApellidoPaciente.setBorder(null);
        jPanel1.add(txtApellidoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 150, -1));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 550, 150, 10));

        txtGenero.setEditable(false);
        txtGenero.setForeground(new java.awt.Color(0, 0, 0));
        txtGenero.setBorder(null);
        jPanel1.add(txtGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 530, 150, -1));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 620, 150, 10));

        txtEps.setEditable(false);
        txtEps.setForeground(new java.awt.Color(0, 0, 0));
        txtEps.setBorder(null);
        jPanel1.add(txtEps, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 600, 150, -1));

        btnAtender.setBackground(new java.awt.Color(103, 160, 174));
        btnAtender.setForeground(new java.awt.Color(255, 255, 255));
        btnAtender.setText("Atender cita");
        btnAtender.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAtender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenderActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtender, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 610, 130, 40));

        jPanel9.setBackground(new java.awt.Color(103, 160, 174));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(103, 160, 174));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Notas");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(853, 190, 240, -1));

        txtNotas.setForeground(new java.awt.Color(0, 0, 0));
        txtNotas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 230, 190, 60));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(103, 160, 174));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Diagnóstico");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 330, 240, -1));

        txtDiagnostico.setForeground(new java.awt.Color(0, 0, 0));
        txtDiagnostico.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 370, 190, 60));

        btnHistorialMedico.setBackground(new java.awt.Color(103, 160, 174));
        btnHistorialMedico.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorialMedico.setText("Ver historial médico");
        btnHistorialMedico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHistorialMedico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistorialMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialMedicoActionPerformed(evt);
            }
        });
        jPanel1.add(btnHistorialMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 660, 170, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseEntered
        exitBtn.setBackground(Color.red);
        lblCerrar.setForeground(Color.white);
    }//GEN-LAST:event_lblCerrarMouseEntered

    private void lblCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseExited
        exitBtn.setBackground(Color.white);
        lblCerrar.setForeground(Color.black);
    }//GEN-LAST:event_lblCerrarMouseExited

    private void barraLateralMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraLateralMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barraLateralMouseDragged

    private void barraLateralMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraLateralMousePressed
        xMouse = evt.getX();
        yMouse= evt.getY();
    }//GEN-LAST:event_barraLateralMousePressed

    private void lblVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseClicked
        this.dispose();
        JFrame v2 = new VentanaMenuMedico(medico);
        v2.setVisible(true);
    }//GEN-LAST:event_lblVolverMouseClicked

    private void lblVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseEntered
        lblRegresar.setBackground(Color.red);
        lblVolver.setForeground(Color.white);
    }//GEN-LAST:event_lblVolverMouseEntered

    private void lblVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseExited
        lblRegresar.setBackground(new Color(103, 160,174));
        lblVolver.setForeground(Color.black);
    }//GEN-LAST:event_lblVolverMouseExited

    private void tablaConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaConsultasMouseClicked
        
        int row = tablaConsultas.getSelectedRow();
        txtCodigo.setText(modelo.getValueAt(row,0).toString());
        
        String codigo = txtCodigo.getText();
        Consulta consulta = controladorCitas.buscarConsulta(codigo);
        
        txtPaciente.setText(consulta.getPaciente().getNombres()+" "+consulta.getPaciente().getApellidos());
        txtFecha.setText(consulta.getFechaAtencion().toString());
        txtHora.setText(consulta.getHora().toString());
        txtMotivo.setText(consulta.getMotivo());   
        txtNombrePaciente.setText(consulta.getPaciente().getNombres());
        txtApellidoPaciente.setText(consulta.getPaciente().getApellidos());
        txtIdentificacionPaciente.setText(consulta.getPaciente().getIdentificacion());
        txtGenero.setText(consulta.getPaciente().getGenero());
        txtTelefono.setText(consulta.getPaciente().getNumTelefono());
        txtEps.setText(consulta.getPaciente().getNombreEps());
        
    }//GEN-LAST:event_tablaConsultasMouseClicked

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarCamposActionPerformed

    private void btnAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderActionPerformed
        if(txtNotas.getText().isEmpty() || txtDiagnostico.getText().isEmpty() || txtValoracion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Existen campos obligatorios para atender la cita");
            return;
        }
        
        Date hoy = new Date();
        LocalDate hoy1 = new  java.sql.Date(hoy.getTime()).toLocalDate();
          
        String codigo = txtCodigo.getText();
        Consulta consulta1 = controladorCitas.buscarConsulta(codigo);
        String notas = txtNotas.getText();
        String diagnostico = txtDiagnostico.getText();
        String valoracion = txtValoracion.getText();
        String estado = "Atendida";
        
        Consulta consulta = new Consulta(medico, consulta1.getPaciente(), consulta1.getHora(), consulta1.getFechaAtencion(), estado, codigo, consulta1.getTipoConsulta(), consulta1.getMotivo(), notas, diagnostico, valoracion);
        
        if(consulta.getFechaAtencion().equals(hoy1)){
            try{
            controladorCitas.actulizarConsulta(consulta);
            JOptionPane.showMessageDialog(null, "Cita Atendida correctamente");
            limpiarCampos();
            actualizarTabla();
            }catch(NullPointerException ex){
            }
        }else {
            JOptionPane.showMessageDialog(null, "Aún no puede atender esta cita!");
            limpiarCampos();
        }
    }//GEN-LAST:event_btnAtenderActionPerformed

    private void btnHistorialMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialMedicoActionPerformed
        if(txtCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el código de la cita para ver el historial del paciente");
            return;
        }

        String codigo = txtCodigo.getText();
        Consulta consulta = controladorCitas.buscarConsulta(codigo);
        this.dispose();
        JFrame v2 = new VentanaHistorialMedicoPaciente(medico, consulta);
        v2.setVisible(true);
    }//GEN-LAST:event_btnHistorialMedicoActionPerformed

    public void limpiarCampos(){
        txtCodigo.setText(null);
        txtPaciente.setText(null);
        txtFecha.setText(null);
        txtHora.setText(null);
        txtNombrePaciente.setText(null);
        txtApellidoPaciente.setText(null);
        txtIdentificacionPaciente.setText(null);
        txtGenero.setText(null);
        txtTelefono.setText(null);
        txtEps.setText(null);
        txtNotas.setText(null);
        txtDiagnostico.setText(null);
        txtMotivo.setText(null);
        txtValoracion.setText(null);
    }
    
    private void actualizarTabla(){
        ArrayList<Consulta> consultas = controladorCitas.conseguirConsultas(medico);
        try{
            for (int i = 0; i < 3 ; i++) {
                for (int j = 0; j < modelo.getRowCount(); j++) {
                    modelo.removeRow(j);
                }
            }
        }catch(NullPointerException e){
        }
            try{
                for (int i = 0; i < consultas.size() ; i++) {
                    Consulta aux = consultas.get(i);
                    Object[] ob = {aux.getCodigo(), aux.getPaciente().getNombres() + " " + aux.getPaciente().getApellidos(), aux.getFechaAtencion(),aux.getHora()};
                    modelo.addRow(ob);
                }
            }catch(NullPointerException e){        
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraLateral;
    private javax.swing.JButton btnAtender;
    private javax.swing.JButton btnHistorialMedico;
    private javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JPanel btnVolver;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JPanel lblRegresar;
    private javax.swing.JLabel lblVolver;
    private javax.swing.JTable tablaConsultas;
    private javax.swing.JTextField txtApellidoPaciente;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDiagnostico;
    private javax.swing.JTextField txtEps;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtIdentificacionPaciente;
    private javax.swing.JTextField txtMotivo;
    private javax.swing.JTextField txtNombrePaciente;
    private javax.swing.JTextField txtNotas;
    private javax.swing.JTextField txtPaciente;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtValoracion;
    // End of variables declaration//GEN-END:variables
}
