
package VistasPaciente;

import Controladores.ControladorHistorialPaciente;
import Modelos.Consulta;
import Modelos.Paciente;
import java.awt.Color;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diazje
 */
public class VentanaHistorialMedico extends javax.swing.JFrame {
    
    int xMouse, yMouse;
    private Paciente paciente;
    DefaultTableModel modelo;
    private ControladorHistorialPaciente controladorHistorial;


    /**
     * Creates new form VentanaHistorialMedico
     */
    public VentanaHistorialMedico(Paciente paciente) {
        initComponents();
        this.paciente = paciente;
        modelo = (DefaultTableModel) tablaHistorial.getModel();
        this.controladorHistorial = new ControladorHistorialPaciente();
        actualizarTablaConsultas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barraLateral = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        lblCerrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHistorial = new javax.swing.JTable();
        btnVolver = new javax.swing.JPanel();
        lblRegresar = new javax.swing.JPanel();
        lblVolver = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBuscarNombre = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        btnBuscarDia = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        dateFiltroDia = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraLateral.setBackground(new java.awt.Color(103, 160, 174));
        barraLateral.setForeground(new java.awt.Color(255, 255, 255));
        barraLateral.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraLateralMouseDragged(evt);
            }
        });
        barraLateral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraLateralMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(103, 160, 174));

        lblCerrar.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        lblCerrar.setForeground(new java.awt.Color(0, 0, 0));
        lblCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-cerrar-ventana-40.png"))); // NOI18N
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblCerrar))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblCerrar))
        );

        javax.swing.GroupLayout barraLateralLayout = new javax.swing.GroupLayout(barraLateral);
        barraLateral.setLayout(barraLateralLayout);
        barraLateralLayout.setHorizontalGroup(
            barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraLateralLayout.createSequentialGroup()
                .addGap(0, 690, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        barraLateralLayout.setVerticalGroup(
            barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraLateralLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(barraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 40));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 29)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(103, 160, 174));
        jLabel1.setText("Historial Medico");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, 30));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(103, 160, 174));
        jLabel2.setText("o");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        tablaHistorial.setBackground(new java.awt.Color(255, 255, 255));
        tablaHistorial.setForeground(new java.awt.Color(103, 160, 174));
        tablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Código", "Medico", "Motivo", "Valoracion", "Notas", "Diagnostico"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaHistorial.setSelectionBackground(new java.awt.Color(103, 160, 174));
        tablaHistorial.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tablaHistorial);
        if (tablaHistorial.getColumnModel().getColumnCount() > 0) {
            tablaHistorial.getColumnModel().getColumn(0).setResizable(false);
            tablaHistorial.getColumnModel().getColumn(1).setResizable(false);
            tablaHistorial.getColumnModel().getColumn(2).setResizable(false);
            tablaHistorial.getColumnModel().getColumn(3).setResizable(false);
            tablaHistorial.getColumnModel().getColumn(4).setResizable(false);
            tablaHistorial.getColumnModel().getColumn(5).setResizable(false);
            tablaHistorial.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 660, 250));

        btnVolver.setBackground(new java.awt.Color(103, 160, 174));

        lblRegresar.setBackground(new java.awt.Color(103, 160, 174));

        lblVolver.setForeground(new java.awt.Color(103, 160, 174));
        lblVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar.png"))); // NOI18N
        lblVolver.setText("jLabel1");
        lblVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVolverMouseExited(evt);
            }
        });

        javax.swing.GroupLayout lblRegresarLayout = new javax.swing.GroupLayout(lblRegresar);
        lblRegresar.setLayout(lblRegresarLayout);
        lblRegresarLayout.setHorizontalGroup(
            lblRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblRegresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        lblRegresarLayout.setVerticalGroup(
            lblRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblRegresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblVolver))
        );

        javax.swing.GroupLayout btnVolverLayout = new javax.swing.GroupLayout(btnVolver);
        btnVolver.setLayout(btnVolverLayout);
        btnVolverLayout.setHorizontalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVolverLayout.createSequentialGroup()
                .addComponent(lblRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(690, Short.MAX_VALUE))
        );
        btnVolverLayout.setVerticalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVolverLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, 730, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo280_1.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 260, 70));

        btnBuscarNombre.setBackground(new java.awt.Color(103, 160, 174));
        btnBuscarNombre.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarNombre.setText("Buscar");
        btnBuscarNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNombreActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 110, 40));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(103, 160, 174));
        jLabel4.setText("Ingrese el dia que desea buscar");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        txtNombre.setBorder(null);
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 140, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 140, 10));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(103, 160, 174));
        jLabel5.setText("Ingrese el nombre del medico");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        btnBuscarDia.setBackground(new java.awt.Color(103, 160, 174));
        btnBuscarDia.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarDia.setText("Buscar");
        btnBuscarDia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDiaActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 110, 40));

        btnConsultas.setBackground(new java.awt.Color(103, 160, 174));
        btnConsultas.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultas.setText("Ver todas mis consultas");
        btnConsultas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 230, 50));
        jPanel1.add(dateFiltroDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseEntered
        exitBtn.setBackground(Color.red);
        lblCerrar.setForeground(Color.white);
    }//GEN-LAST:event_lblCerrarMouseEntered

    private void lblCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseExited
        exitBtn.setBackground(new Color(103, 160,174));
        lblCerrar.setForeground(Color.black);
    }//GEN-LAST:event_lblCerrarMouseExited

    private void barraLateralMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraLateralMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barraLateralMouseDragged

    private void barraLateralMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraLateralMousePressed
        xMouse = evt.getX();
        yMouse= evt.getY();
    }//GEN-LAST:event_barraLateralMousePressed

    private void lblVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseClicked
        this.dispose();
        JFrame v2 = new VentanaMenuPa(paciente);
        v2.setVisible(true);
    }//GEN-LAST:event_lblVolverMouseClicked

    private void lblVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseEntered
        lblRegresar.setBackground(Color.red);
        lblVolver.setForeground(Color.white);
    }//GEN-LAST:event_lblVolverMouseEntered

    private void lblVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseExited
        lblRegresar.setBackground(new Color(103, 160,174));
        lblVolver.setForeground(Color.black);
    }//GEN-LAST:event_lblVolverMouseExited

    private void btnBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNombreActionPerformed
        if(txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el nombre del medico que desea buscar");
        }else {
            String datoNombre = txtNombre.getText();        
            Consulta validarMedico = controladorHistorial.buscarConsultaMedico(datoNombre);
            if(validarMedico != null){
                String[] titulos = new String[] {"Estado", "Codigo", "Medico", "Motivo", "Valoracion", "Notas", "Diagnostico"};
                modelo.setColumnIdentifiers(titulos);
                tablaHistorial.setModel(modelo); 
                limpiarCampos();
                actualizarTablaMedico(datoNombre);
            }else {
                JOptionPane.showMessageDialog(null, "El medico buscado no cuenta con colsutas atendidas en su historial");
            }
        }
    }//GEN-LAST:event_btnBuscarNombreActionPerformed

    private void btnBuscarDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDiaActionPerformed
        if(dateFiltroDia.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Ingrese el numero del dia que desea buscar en su historial");
        }else {
            Date fecha = dateFiltroDia.getDate();
            LocalDate fechaDia = new java.sql.Date(fecha.getTime()).toLocalDate();
            Consulta validarFecha = controladorHistorial.buscarConsultaFecha(fechaDia);
            if(validarFecha != null) {
                String [] titulos = new String[] {"Estado", "Codigo", "Fecha", "Motivo", "Valoracion", "Notas", "Diagnostico"};
                modelo.setColumnIdentifiers(titulos);
                tablaHistorial.setModel(modelo);
                limpiarCampos();
                actualizarTablaFecha(fechaDia);
            }else {
                JOptionPane.showMessageDialog(null, "El dia buscado no cuenta con consultas atendidas");
            }
        }
    }//GEN-LAST:event_btnBuscarDiaActionPerformed

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed
        String [] titulos = new String[] {"Fecha", "Codigo", "Fecha", "Motivo", "Valoracion", "Notas", "Diagnostico"};
        modelo.setColumnIdentifiers(titulos);
        tablaHistorial.setModel(modelo);
        actualizarTablaConsultas();
    }//GEN-LAST:event_btnConsultasActionPerformed

    public void limpiarCampos(){
        dateFiltroDia.setDate(null);
        txtNombre.setText(null);
    }
    
    
    public void actualizarTablaFecha(LocalDate datoFecha){
        
        ArrayList<Consulta> consultas = controladorHistorial.conseguirConsultasFecha(paciente, datoFecha);
        
        try{
            for (int i = 0; i < 3 ; i++) {
                for (int j = 0; j < modelo.getRowCount(); j++) {
                    modelo.removeRow(j);
                }
            }
        }catch(NullPointerException e){
        }
            try{
                for (int i = 0; i < consultas.size() ; i++) {                    
                      Consulta aux = consultas.get(i);
                      Object[] ob = {aux.getEstado() , aux.getCodigo(), aux.getFechaAtencion(), aux.getMotivo(), aux.getValoracion(), aux.getNotas(), aux.getDiagnostico()};
                      modelo.addRow(ob);                     
                }
            }catch(NullPointerException e){        
        } 
    }

    public void actualizarTablaMedico(String nombre){
        
        ArrayList<Consulta> consultas = controladorHistorial.conseguirConsultasMedicoN(nombre, paciente);
        
        try{
            for (int i = 0; i < 3 ; i++) {
                for (int j = 0; j < modelo.getRowCount(); j++) {
                    modelo.removeRow(j);
                }
            }
        }catch(NullPointerException e){
        }
            try{
                for (int i = 0; i < consultas.size() ; i++) {
                      Consulta aux = consultas.get(i);
                      Object[] ob = {aux.getEstado(), aux.getCodigo(), aux.getMedico().getNombres() + " " + aux.getMedico().getApellidos(), aux.getMotivo(), aux.getValoracion(), aux.getNotas(),aux.getDiagnostico()};
                      modelo.addRow(ob);  
                }                   
            }catch(NullPointerException e){        
        } 
    }
    
    public void actualizarTablaConsultas(){
        
        ArrayList<Consulta> consultas = controladorHistorial.conseguirConsultasTodas(paciente);
        
        try{
            for (int i = 0; i < 3 ; i++) {
                for (int j = 0; j < modelo.getRowCount(); j++) {
                    modelo.removeRow(j);
                }
            }
        }catch(NullPointerException e){
        }
            try{
                for (int i = 0; i < consultas.size() ; i++) {
                      Consulta aux = consultas.get(i);
                      Object[] ob = {aux.getFechaAtencion(), aux.getCodigo(), aux.getMedico().getNombres() + " " + aux.getMedico().getApellidos(), aux.getMotivo(), aux.getValoracion(), aux.getNotas(),aux.getDiagnostico()};
                      modelo.addRow(ob);  
                }                   
            }catch(NullPointerException e){        
        } 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorialMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorialMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorialMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaHistorialMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraLateral;
    private javax.swing.JButton btnBuscarDia;
    private javax.swing.JButton btnBuscarNombre;
    private javax.swing.JButton btnConsultas;
    private javax.swing.JPanel btnVolver;
    private com.toedter.calendar.JDateChooser dateFiltroDia;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JPanel lblRegresar;
    private javax.swing.JLabel lblVolver;
    private javax.swing.JTable tablaHistorial;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
